# Architecture-agnostic system config for the Milk-V Duo S badge.
# Everything here is identical whether the ARM (aarch64) or RISC-V (riscv64)
# large core boots. Nothing arch-specific belongs in this file.
{ pkgs, lib, ... }:
{
  networking.hostName = "nixbadge-duos";

  # The SD image ships an ext4 root sized exactly to the store closure, so a
  # fresh card boots 100% full no matter how large the card is. These two
  # options fix that on every boot, in order:
  #   growPartition   -> growpart.service extends the last MBR partition
  #                      (NIXOS_ROOT, mmcblk0p2) to the end of the card.
  #   x-systemd.growfs -> systemd-growfs-root.service then grows the ext4 to
  #                      fill the new partition, online.
  # Both are no-ops once the card is full, so they are safe to leave on.
  # The root mount lives here, not in core-*.nix, because it is identical on
  # both cores and the two systems share one root partition.
  boot.growPartition = true;

  fileSystems."/" = {
    device = "/dev/disk/by-label/NIXOS_ROOT";
    fsType = "ext4";
    options = [ "x-systemd.growfs" ];
  };

  # The FAT boot partition, so swap-core can reach fip.bin and the per-core
  # extlinux trees without a manual mount.
  #
  # WARNING: this partition does NOT hold a stock NixOS boot layout. It holds
  # the dual-core tree that pkgs/sdcard/make-boot-dir.nix builds:
  #   /fip.bin /fip-arm.bin /fip-riscv.bin
  #   /arm/nixos/... /riscv/nixos/...
  #   /extlinux/extlinux.conf   (a copy of the active core's, paths rewritten
  #                              from ../nixos/ to /arm/nixos/ or /riscv/nixos/)
  # A `nixos-rebuild switch` ON THE BADGE would run the
  # generic-extlinux-compatible installer against /boot, write its own
  # /boot/nixos plus a single-core extlinux.conf with relative ../nixos/ paths,
  # and leave fip.bin alone. The board would still boot, but the dual-core
  # layout and swap-core would be broken until the card is reflashed. Build
  # images on the dev host, do not rebuild in place.
  #
  # nofail keeps a missing or damaged boot partition from blocking the boot.
  # The rootfs does not need it, only tooling does.
  fileSystems."/boot" = {
    device = "/dev/disk/by-label/BOOT";
    fsType = "vfat";
    options = [ "nofail" ];
  };

  # 2 GB swapfile at /swap on the root filesystem. NixOS creates and mkswaps it;
  # change `size` (MiB) to resize.
  swapDevices = [ { device = "/swap"; size = 2048; } ];

  # The image ships the rootfs sized to the store closure, so on first boot the
  # 2 GB swapfile does not fit until x-systemd.growfs has grown / to fill the
  # card. NixOS's generated mkswap-swap.service otherwise races that grow and
  # dd's into a still-full fs (dd stops at ENOSPC, mkswap fails). Order it after
  # the online resize. systemd-growfs-root.service always exists (generated by
  # the "/" x-systemd.growfs mount option) and is a fast no-op once the card is
  # full, so this is safe on every subsequent boot too.
  systemd.services.mkswap-swap = {
    after = [ "systemd-growfs-root.service" ];
    wants = [ "systemd-growfs-root.service" ];
  };

  # (The SARADC auto-calibration service was removed with the Zig rewrite: the
  # tool no longer does userspace calibration -- it reads battery + rails straight
  # from the kernel sysfs power_supply + iio-rescale meters (VSEL/VBAT dividers,
  # J6 direct), which are kernel-scaled, so there is no per-badge factor to
  # calibrate. See pkgs/badge/nix-badge/ and the &saradc dtsi nodes.)

  # /dev/gpiochip* default to root-only (crw------- root), so nix-badge power's
  # VBUS-present + fault reads via the GPIO uAPI only work as root. The boot
  # SARADC calibrate runs as root so it succeeds, but the badge user's
  # `nix-badge power` then shows every GPIO line as "unknown". The badge user
  # already lists the gpio group, but the group did not exist (so it was silently
  # dropped) and the chardevs had no group access. Create the group and grant it
  # the gpio chardevs so the meter reads VBUS + faults without root.
  users.groups.gpio = { };
  services.udev.extraRules = ''
    SUBSYSTEM=="gpio", KERNEL=="gpiochip*", GROUP="gpio", MODE="0660"
  '';

  # 24 WS2812 LEDs on the SPI3 MOSI line (40-pin header pin 19). The service
  # starts in the initrd and keeps running after switch_root, so the ring shows
  # life from very early boot. See modules/duo-s/leds.nix for the option set and
  # the nixbadge-leds CLI.
  nixbadge.leds = {
    enable = true;
    count = 24;
  };

  # Networking via NetworkManager: it manages eth0 (auto-connects wired) and
  # wlan0 once the AIC8800 WiFi comes up. wpa_supplicant backend because the
  # AIC8800 is a fullMAC driver that iwd handles poorly. NetworkManager does its
  # own DHCP, so the scripted dhcpcd is off. Public nameservers as a fallback so
  # resolution works even if DHCP hands over no resolver.
  networking.networkmanager = {
    enable = true;
    wifi.backend = "wpa_supplicant";
  };
  networking.useDHCP = false;
  networking.nameservers = lib.mkDefault [
    "1.1.1.1"
    "9.9.9.9"
  ];

  # Minimal headless userland. Flesh out with the badge services later.
  users.users.badge = {
    isNormalUser = true;
    extraGroups = [ "wheel" "dialout" "gpio" "networkmanager" ];
    # TODO: replace with a real key before flashing.
    openssh.authorizedKeys.keys = [ ];
    initialPassword = "nixbadge";
  };

  # Give root a password so the systemd emergency/rescue shell (sulogin) can open
  # on the serial console. Without it root is locked and a bad boot prints
  # "Cannot open access to console, the root account is locked", leaving no way to
  # recover over serial. Root still cannot log in over ssh (PermitRootLogin = no),
  # so this only matters for local serial/console access.
  users.users.root.initialPassword = "nixbadge";
  # Allow a passwordless root shell in the stage-1 (initrd) systemd emergency
  # target, so an initrd failure (e.g. the root device or NixOS closure not found)
  # is recoverable over serial too.
  boot.initrd.systemd.emergencyAccess = true;

  services.openssh = {
    enable = true;
    settings.PermitRootLogin = "no";
  };

  # /dev/i2c-1 for the SAO SSD1306 OLED (IIC1, enabled in the common dtsi). The
  # bling engine and `nix-badge oled` drive the panel from userspace via i2c-dev.
  boot.kernelModules = [ "i2c-dev" ];

  environment.systemPackages = with pkgs; [
    htop
    i2c-tools
    usbutils
    # gpioinfo / gpioget / gpioset. The DTS gives porta and portb real line
    # names, so gpioinfo reads as a wiring diagram. Needed to poke things like
    # sao-power-en by hand while bringing the board up.
    libgpiod
    # Switch the active core from the badge itself. It swaps fip.bin AND
    # extlinux/extlinux.conf together, which is the part that is easy to get
    # wrong by hand: copying only fip.bin leaves the new core's U-Boot loading
    # the other core's kernel, and it stops at "Bad Linux RISCV Image magic!".
    (import ../../pkgs/sdcard/swap-core.nix { inherit pkgs; })
  ];

  # Keep the closure small, this is going on an SD card.
  documentation.enable = lib.mkDefault false;
  documentation.nixos.enable = lib.mkDefault false;

  system.stateVersion = "26.05";
}
