# Architecture-agnostic system config for the Milk-V Duo S badge.
# Everything here is identical whether the ARM (aarch64) or RISC-V (riscv64)
# large core boots. Nothing arch-specific belongs in this file.
{ pkgs, lib, ... }:
let
  # The default OLED/LED content tree (Bad Apple + info screens + demoscene
  # effects under oled.d/, LED patterns under bling.d/, the shared font/draw
  # library under lib/), baked into the store. /etc/nixbadge is seeded FROM this
  # by nixbadge-content.service (below) as writable, hackable symlinks -- the
  # store path is the symlink target, so `ls -l /etc/nixbadge/oled.d` shows each
  # screen's exact Nix provenance.
  contentTree = import ../../pkgs/badge/bling-content/etc.nix {
    pkgs = pkgs.buildPackages;
    height = 64;
    fps = 60;
    durationSeconds = null;
    keyframeInterval = 60;
  };
in
{
  networking.hostName = "nixbadge-duos";

  # zram: compressed RAM swap, the badge's single biggest responsiveness win. The
  # fix Bad Apple screen materialises its 13140 delta frames LAZILY as it plays,
  # each becoming a boxed Nix Value pinned by the frames list -- so the shared
  # Engine grows from ~60 MB toward ~300 MB over a minute of playback and, on the
  # 351 MB badge, crosses RAM and thrashes to the slow SD `/swap` file (measured:
  # per-frame eval 5 ms -> 23 s, PSI memory `full` > 40 %, iowait ~80 %). 1-bit
  # video deltas compress ~5-10x with zstd, so zram absorbs that working set in a
  # fraction of the RAM and refaults become microsecond decompresses instead of
  # SD reads. Sized above RAM (it compresses) and left at the default priority,
  # which is higher than the SD `/swap` file (-1) -- so zram fills first and the
  # SD file stays only as an overflow backstop. Both cores are memory-tight, so
  # this lives in common.nix.
  zramSwap = {
    enable = true;
    algorithm = "zstd";
    memoryPercent = 150;
  };

  # The SD image ships an ext4 root sized exactly to the store closure, so a
  # fresh card boots 100% full no matter how large the card is. These two
  # options fix that on every boot, in order:
  #   growPartition   -> growpart.service extends the last MBR partition
  #                      (NIXOS_ROOT, mmcblk0p2) to the end of the card.
  #   x-systemd.growfs -> systemd-growfs-root.service then grows the ext4 to
  #                      fill the new partition, online.
  # Both are no-ops once the card is full, so they are safe to leave on.
  # The root mount lives here, not in core-*.nix, because it is identical on
  # both cores and the two systems share one root partition.
  boot.growPartition = true;

  fileSystems."/" = {
    device = "/dev/disk/by-label/NIXOS_ROOT";
    fsType = "ext4";
    options = [ "x-systemd.growfs" ];
  };

  # The FAT boot partition, so swap-core can reach fip.bin and the per-core
  # extlinux trees without a manual mount.
  #
  # WARNING: this partition does NOT hold a stock NixOS boot layout. It holds
  # the dual-core tree that pkgs/sdcard/make-boot-dir.nix builds:
  #   /fip.bin /fip-arm.bin /fip-riscv.bin
  #   /arm/nixos/... /riscv/nixos/...
  #   /extlinux/extlinux.conf   (a copy of the active core's, paths rewritten
  #                              from ../nixos/ to /arm/nixos/ or /riscv/nixos/)
  # A `nixos-rebuild switch` ON THE BADGE would run the
  # generic-extlinux-compatible installer against /boot, write its own
  # /boot/nixos plus a single-core extlinux.conf with relative ../nixos/ paths,
  # and leave fip.bin alone. The board would still boot, but the dual-core
  # layout and swap-core would be broken until the card is reflashed. Build
  # images on the dev host, do not rebuild in place.
  #
  # nofail keeps a missing or damaged boot partition from blocking the boot.
  # The rootfs does not need it, only tooling does.
  fileSystems."/boot" = {
    device = "/dev/disk/by-label/BOOT";
    fsType = "vfat";
    options = [ "nofail" ];
  };

  # 2 GB swapfile at /swap on the root filesystem. NixOS creates and mkswaps it;
  # change `size` (MiB) to resize.
  swapDevices = [ { device = "/swap"; size = 2048; } ];

  # The image ships the rootfs sized to the store closure, so on first boot the
  # 2 GB swapfile does not fit until x-systemd.growfs has grown / to fill the
  # card. NixOS's generated mkswap-swap.service otherwise races that grow and
  # dd's into a still-full fs (dd stops at ENOSPC, mkswap fails). Order it after
  # the online resize. systemd-growfs-root.service always exists (generated by
  # the "/" x-systemd.growfs mount option) and is a fast no-op once the card is
  # full, so this is safe on every subsequent boot too.
  systemd.services.mkswap-swap = {
    after = [ "systemd-growfs-root.service" ];
    wants = [ "systemd-growfs-root.service" ];
  };

  # No coredumps. The embedded fix evaluator aborts on the known GC bug (draw-heavy
  # OLED screens); capturing a core of the ~80 MB Engine on every crash is wasteful
  # I/O and could fill the 351 MB badge's rootfs. Turn off the systemd-coredump
  # handler AND override its `core_pattern = "core"` default: pointing core_pattern
  # at /dev/null disables dumping entirely -- the kernel refuses to write a core to
  # a non-regular file, so nothing is generated (no program/store-path dependency).
  systemd.coredump.enable = false;
  boot.kernel.sysctl."kernel.core_pattern" = "/dev/null";

  # (The SARADC auto-calibration service was removed with the Zig rewrite: the
  # tool no longer does userspace calibration -- it reads battery + rails straight
  # from the kernel sysfs power_supply + iio-rescale meters (VSEL/VBAT dividers,
  # J6 direct), which are kernel-scaled, so there is no per-badge factor to
  # calibrate. See pkgs/badge/nix-badge/ and the &saradc dtsi nodes.)

  # /dev/gpiochip* default to root-only (crw------- root), so nix-badge power's
  # VBUS-present + fault reads via the GPIO uAPI only work as root. The boot
  # SARADC calibrate runs as root so it succeeds, but the badge user's
  # `nix-badge power` then shows every GPIO line as "unknown". The badge user
  # already lists the gpio group, but the group did not exist (so it was silently
  # dropped) and the chardevs had no group access. Create the group and grant it
  # the gpio chardevs so the meter reads VBUS + faults without root.
  users.groups.gpio = { };
  services.udev.extraRules = ''
    SUBSYSTEM=="gpio", KERNEL=="gpiochip*", GROUP="gpio", MODE="0660"
  '';

  # 24 WS2812 LEDs on the SPI3 MOSI line (40-pin header pin 19). The service
  # starts in the initrd and keeps running after switch_root, so the ring shows
  # life from very early boot. See modules/duo-s/bling.nix for the option set and
  # the nixbadge-bling CLI.
  nixbadge.bling = {
    enable = true;
    count = 24;
  };

  # OLED engine: a SET of pure-Nix screens the embedded fix evaluator
  # applies per frame, ALL sharing ONE fix Engine (a ScreenSet -- one Value/chunk
  # heap for the whole set, not one per screen; five separate Engines would OOM
  # the 351 MB badge). The USER long-press / SIGUSR2 cycles through them:
  #   1. the FULL Bad Apple song (the marquee "it's the Nix Badge" demo)
  #   2-5. the Gallant-font info screens: battery, load, power, clock
  #   6. currentsystem -- renders builtins.currentSystem, an on-theme readout
  #      (the ARM<->RISC-V core swap IS which system fix reports: "aarch64-linux")
  # aarch64 only (the evaluator is ARM-side; the riscv core accepts the flags but
  # skips them, falling back to the computed Zig screens). Bad Apple alone measured
  # ~81 MB RSS while shown (frames are chunk constants -- it plateaus); the info
  # screens are tiny lambdas sharing that same Engine, so the set's steady-state
  # RSS is dominated by whichever heavy screen (Bad Apple) has been evaluated.
  # buildPackages so the ffmpeg transcode + Nix generation run on the build host.
  #
  # 128x64 panel (swapped in on the bench). The screens read scope.height, so they
  # lay out to the taller panel; the SSD1306 init parameterises for 64 rows.
  nixbadge.oled.height = 64;

  # Dir-based content at /etc/nixbadge: the runtime scans oled.d/*.nix (--eval-dir), and a
  # screen's `<nixbadge/lib/...>` imports resolve through nix-badge's `nixbadge=/etc/nixbadge`
  # search path (both backends). The font/draw library lives once under lib/, imported by
  # every screen. Bad Apple leads (baked for the 128x64 panel @60 fps, DELTA codec: per-frame
  # (offset,byte) changes, 2/int, applied to a persistent framebuffer, flushing only changed
  # columns -> 60 fps under 1 MHz I2C; keyframeInterval=60 self-heals once/second), then the
  # info screens, then the demoscene effects.
  #
  # /etc/nixbadge is a REAL, writable, HACKABLE directory -- NOT a read-only store symlink.
  # nixbadge-content.service seeds it from `contentTree` with a three-way rule per file that
  # systemd-tmpfiles' L/L+ cannot express (plain L never repoints a symlink; L+ also clobbers
  # a user's regular file):
  #   * missing           -> symlink to the store default
  #   * already a symlink  -> repoint to the (new) store path   [clobber the stale link]
  #   * a regular FILE     -> LEFT ALONE (the user's own hacked screen/effect)
  # So `cp` a default over its symlink, edit in place, and your copy survives every rebuild;
  # `rm` your copy and the default symlink returns on the next boot. Defaults removed upstream
  # leave a dangling symlink, which the seed prunes. The mutable runtime state (leds.conf,
  # oled.state, oled.backend) also lives directly under /etc/nixbadge now (moved off
  # /var/lib/nix-badge), so the badge's whole mutable surface is one hackable folder.
  nixbadge.oled.evalDir = "/etc/nixbadge/oled.d";

  systemd.tmpfiles.rules = [ "d /etc/nixbadge 0755 root root -" ];

  systemd.services.nixbadge-content = {
    description = "Seed /etc/nixbadge with default OLED/LED content (hackable in place)";
    wantedBy = [ "multi-user.target" ];
    before = [ "nixbadge-oled.service" ];
    after = [ "systemd-tmpfiles-setup.service" ];
    unitConfig.ConditionPathIsReadWrite = "/etc";
    path = [ pkgs.coreutils pkgs.findutils ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      set -eu
      src="${contentTree}"
      dst=/etc/nixbadge
      # Migration: earlier builds shipped /etc/nixbadge as a read-only store symlink
      # (environment.etc). If one lingers, drop it so we can make a real writable dir.
      [ -L "$dst" ] && rm -f "$dst"
      mkdir -p "$dst"
      # (Re)link every default file; never touch a user's regular-file override.
      while IFS= read -r -d "" f; do
        rel="''${f#"$src"/}"
        target="$dst/$rel"
        mkdir -p "$(dirname "$target")"
        if [ -f "$target" ] && [ ! -L "$target" ]; then
          continue          # user's own hacked file -> leave it
        fi
        ln -sfn "$f" "$target"   # missing or symlink -> point at the store default
      done < <(find "$src" \( -type f -o -type l \) -print0)
      # Prune defaults removed upstream (now-dangling symlinks); never touches regular files.
      find "$dst" -type l ! -exec test -e {} \; -delete
    '';
  };

  # Networking via NetworkManager: it manages eth0 (auto-connects wired) and
  # wlan0 once the AIC8800 WiFi comes up. wpa_supplicant backend because the
  # AIC8800 is a fullMAC driver that iwd handles poorly. NetworkManager does its
  # own DHCP, so the scripted dhcpcd is off. Public nameservers as a fallback so
  # resolution works even if DHCP hands over no resolver.
  networking.networkmanager = {
    enable = true;
    wifi.backend = "wpa_supplicant";
  };
  networking.useDHCP = false;
  networking.nameservers = lib.mkDefault [
    "1.1.1.1"
    "9.9.9.9"
  ];

  # Minimal headless userland. Flesh out with the badge services later.
  users.users.badge = {
    isNormalUser = true;
    extraGroups = [ "wheel" "dialout" "gpio" "networkmanager" ];
    # TODO: replace with a real key before flashing.
    openssh.authorizedKeys.keys = [ ];
    initialPassword = "nixbadge";
  };

  # Give root a password so the systemd emergency/rescue shell (sulogin) can open
  # on the serial console. Without it root is locked and a bad boot prints
  # "Cannot open access to console, the root account is locked", leaving no way to
  # recover over serial. Root still cannot log in over ssh (PermitRootLogin = no),
  # so this only matters for local serial/console access.
  users.users.root.initialPassword = "nixbadge";
  # Allow a passwordless root shell in the stage-1 (initrd) systemd emergency
  # target, so an initrd failure (e.g. the root device or NixOS closure not found)
  # is recoverable over serial too.
  boot.initrd.systemd.emergencyAccess = true;

  services.openssh = {
    enable = true;
    settings.PermitRootLogin = "no";
  };

  # /dev/i2c-1 for the SAO SSD1306 OLED (IIC1, enabled in the common dtsi). The
  # oled engine and `nix-badge oled` drive the panel from userspace via i2c-dev.
  boot.kernelModules = [ "i2c-dev" ];

  environment.systemPackages = with pkgs; [
    htop
    i2c-tools
    usbutils
    # gpioinfo / gpioget / gpioset. The DTS gives porta and portb real line
    # names, so gpioinfo reads as a wiring diagram. Needed to poke things like
    # sao-power-en by hand while bringing the board up.
    libgpiod
    # Switch the active core from the badge itself. It swaps fip.bin AND
    # extlinux/extlinux.conf together, which is the part that is easy to get
    # wrong by hand: copying only fip.bin leaves the new core's U-Boot loading
    # the other core's kernel, and it stops at "Bad Linux RISCV Image magic!".
    (import ../../pkgs/sdcard/swap-core.nix { inherit pkgs; })
  ];

  # Keep the closure small, this is going on an SD card.
  documentation.enable = lib.mkDefault false;
  documentation.nixos.enable = lib.mkDefault false;

  system.stateVersion = "26.05";
}
