#ifndef __CVIPART_H__
#define __CVIPART_H__
/*
 * cvipart.h authored for Milk-V Duo S SD boot.
 * In the Sophgo SDK this is generated by mkcvipart.py from a partition XML.
 * We define the minimal subset needed by cv181x-asic.h.
 *
 * cv181x-asic.h does #undef CONFIG_ENV_OFFSET and #undef CONFIG_ENV_SIZE
 * before including this file, so we redefine them here.
 */

#define CONFIG_ENV_OFFSET     0x880000
#define CONFIG_ENV_SIZE       0x20000
#define CONFIG_ENV_IS_IN_MMC  1
#define ROOTFS_DEV            "/dev/mmcblk0p3"
#define PART_LAYOUT           ""
#define PARTS_OFFSET          ""

#endif /* __CVIPART_H__ */
