# U-Boot for Milk-V Duo S (Sophgo SG2000, aarch64).
# Builds from sophgo/u-boot-2021.10 branch sg200x-dev commit a955e4df4d034b214416e3913e68b2d90ebce714.
# Produces $out/u-boot-raw.bin (= u-boot.bin, the LOADER_2ND blob for fip packing).
#
# Board glue authored here (not from the SDK build/ tree):
#   configs/cvitek_sg2000_milkv_duos_glibc_arm64_sd_defconfig  (placed via postPatch)
#   board/cvitek/cvi_board_init.c                               (arm variant: no prior_stage_fdt_address)
#   include/cvi_board_memmap.h                                  (memory map for Duo S 512MB)
#   include/cvipart.h                                           (minimal SD partition defs)
#
# Investigation findings:
#   The vendor tree (a955e4df) does NOT contain arch/arm/dts/cv181x_cv181xasic.dts or any
#   cv181x arm U-Boot control DTS. The arm dts/Makefile expects arch/arm/dts/$(CHIP)_$(CVIBOARD).dtb
#   (= cv181x_cv181xasic.dtb) but no source exists in the tree.
#
#   CONFIG_OF_PRIOR_STAGE was the original approach (BL31/ATF passes FDT ptr at 0x80080000). But in a
#   clean Nix build nothing writes a valid DTB at 0x80080000, so prior_stage_fdt_address is
#   garbage and fdtdec_setup() reads /memory from an invalid pointer and hangs before U-Boot
#   has any console output.
#
#   Fix: CONFIG_OF_EMBED. We provide a minimal standalone control DTS placed via postPatch at
#   arch/arm/dts/cv181x_cv181xasic.dts. U-Boot compiles it and links it in as __dtb_dt_begin,
#   so gd->fdt_blob is valid from fdtdec_setup() onward without requiring a runtime FDT pointer.
#   The DTS is self-contained (no SDK header includes) with the minimal nodes needed:
#     - /memory at 0x80000000 / 512 MB
#     - ARM Cortex-A53 cpu node with GIC interrupt controller
#     - uart0 (snps,dw-apb-uart at 0x04140000, console)
#     - cv-sd@4310000 (cvitek,cv181x-sd) for SD boot
#   The prior_stage_fdt_address variable is NO LONGER defined when OF_PRIOR_STAGE is removed;
#   cvi_board_init.c (arm variant) matches the riscv variant and omits that definition.
#
# Patches applied:
#   Patch 1: Add config SYS_TEXT_BASE hex to board/cvitek/cv181x/Kconfig.
#     Same reason as the RISC-V build: the vendor Kconfig has no SYS_TEXT_BASE entry,
#     so the defconfig value is silently dropped and board_f.c / efi_runtime.c get
#     CONFIG_SYS_TEXT_BASE undeclared.
#   Patch 2: Override CONFIG_BOOTCOMMAND and CONFIG_EXTRA_ENV_SETTINGS in cv181x-asic.h.
#     The vendor SD boot command uses hush if/then and riscv earlycon args. We replace
#     it with a clean sysboot/extlinux command targeting /extlinux/extlinux.conf on
#     mmc 0:1 (FAT partition 1). Load addresses are non-overlapping with U-Boot text
#     (0x80200000), FSBL_UNZIP region (0x81800000-0x82800000), and each other.
#   Patch 3: Provide the missing cv181x arm U-Boot control DTS (arch/arm/dts/cv181x_cv181xasic.dts).
#     SD node compatible "cvitek,cv181x-sd" matches sdhci-mars.c of_match. SD pinmux
#     (SDIO0 pad setup) is handled in sdhci-mars.c cvi_sdhci_probe() via
#     cvi_sdio0_pad_function()/cvi_sdio0_pad_setting() - no board_init pinmux needed.
{ pkgs }:
let
  ubootSrc = pkgs.fetchFromGitHub {
    owner = "sophgo";
    repo  = "u-boot-2021.10";
    rev   = "a955e4df4d034b214416e3913e68b2d90ebce714";
    hash  = "sha256-n3Me9Q0knGv6rl4gdanHovkEf3pu9iVlaNJqCWe8hYU=";
  };

  cc = pkgs.pkgsCross.aarch64-multiplatform.stdenv.cc;
  crossPrefix = cc.targetPrefix;

  defconfig = ./cvitek_sg2000_milkv_duos_glibc_arm64_sd_defconfig;
  boardInit = ./cvi_board_init.c;
  memmap    = ./duos-arm-uboot-memmap.h;
  cvipart   = ./cvipart.h;
in
pkgs.stdenv.mkDerivation {
  pname   = "uboot-duos-arm";
  version = "2021.10-a955e4d";

  src = ubootSrc;

  nativeBuildInputs = with pkgs; [
    cc
    gnumake
    bison
    flex
    bc
    dtc
    openssl
    python3
    swig
    ncurses
    perl
  ];

  postPatch = ''
    # Stub the SCM version so scripts/setlocalversion skips git entirely.
    # setlocalversion checks for .scmversion first (line ~38) and returns
    # its contents, bypassing all git calls. An empty file produces no
    # suffix, which is the same behaviour as the riscv build (no git there).
    echo -n "" > .scmversion

    # Place authored defconfig
    cp ${defconfig} configs/cvitek_sg2000_milkv_duos_glibc_arm64_sd_defconfig

    # Place board init (gitignored in vendor tree, generated by SDK normally)
    cp ${boardInit} board/cvitek/cvi_board_init.c

    # Place memory map header (all CVIMMAP_ defines for Duo S 512MB)
    cp ${memmap} include/cvi_board_memmap.h

    # Place partition definitions header (generated by mkcvipart.py in SDK)
    cp ${cvipart} include/cvipart.h

    # Patch 1: Add SYS_TEXT_BASE Kconfig symbol to cv181x board Kconfig.
    # The vendor Kconfig has no config SYS_TEXT_BASE entry, so the defconfig
    # value is silently dropped and board_f.c / efi_runtime.c get
    # CONFIG_SYS_TEXT_BASE undeclared. Adding a hex entry here mirrors what
    # other arm mach Kconfigs do (aspeed, owl, stm32mp, etc.).
    cat >> board/cvitek/cv181x/Kconfig <<'EOF'

config SYS_TEXT_BASE
	hex "Text Base"
	default 0x80200000
	help
	  U-Boot text/code base address in DRAM. For Milk-V Duo S the
	  SDK places U-Boot at DRAM_BASE + 2 MB = 0x80200000, per
	  build/boards/cv181x/sg2000_milkv_duos_glibc_arm64_sd/memmap.py.
EOF

    # Patch 2: Override the vendor boot flow in cv181x-asic.h.
    # The vendor header defines CONFIG_BOOTCOMMAND (for SD boot) using a hush
    # if/then sequence ("if test $? -eq 0; then ..."), which fails at runtime
    # because hush is not enabled by default in this defconfig.  It also sets
    # othbootargs to "earlycon=sbi riscv.fwsz=..." - leftover RISC-V env.
    # We replace CONFIG_BOOTCOMMAND with a minimal sysboot/extlinux invocation
    # and replace CONFIG_EXTRA_ENV_SETTINGS to remove the riscv junk.
    #
    # Load address map (512 MB DRAM at 0x80000000, ION reserve at 0x9A600000):
    #   0x80200000  U-Boot text (SYS_TEXT_BASE, must not overlap)
    #   0x81000000  kernel Image (kernel_addr_r; ~112 MB room up to fdt at 0x88000000)
    #   0x82000000  sysboot script load / scriptaddr (used before kernel load)
    #   0x88000000  FDT (fdt_addr_r; small, well above kernel)
    #   0x8a000000  initrd (ramdisk_addr_r; ~145 MB room up to ION at 0x9A600000)
    # sysboot reads kernel_addr_r, fdt_addr_r, ramdisk_addr_r (with _r suffix)
    # from the environment; scriptaddr is used without _r suffix.
    # sysboot reads /extlinux/extlinux.conf from mmc 0:1 (FAT partition 1),
    # derives kernel, fdt, and initrd load addrs from the env vars above,
    # and calls booti.  No hush if/then required.
    python3 - <<'ENDPY'
with open("include/configs/cv181x-asic.h", "r") as f:
    src = f.read()

# Replace the entire #ifdef CONFIG_USE_DEFAULT_ENV block's BOOTCOMMAND/EXTRA_ENV
# definitions with our clean extlinux boot.
# Strategy: append our overrides at the very end (before the final #endif guard),
# after all the vendor definitions.  Since cv181x-asic.h does #undef CONFIG_BOOTCOMMAND
# at the top and redefines at the bottom inside #ifdef CONFIG_USE_DEFAULT_ENV,
# we just need to add another #undef/#define at the file end to win.

insert = r"""
/* BadgeOS override: replace vendor FIT/hush boot with NixOS extlinux/sysboot.
 * sysboot mmc 0:1 any <scriptaddr> /arm/extlinux/extlinux.conf
 * - mmc 0:1  = SD card (mmc0), partition 1 (FAT with extlinux.conf)
 * - scriptaddr 0x82000000: safe load addr for the extlinux conf text
 * - kernel_addr_r/fdt_addr_r/ramdisk_addr_r: _r suffix required by sysboot/pxe_utils
 * - Non-overlapping with U-Boot text (0x80200000) and ION reserve (0x9A600000)
 * - No hush if/then, no FIT, no riscv earlycon.
 *
 * The path is PER CORE (/arm/, and /riscv/ in the RISC-V U-Boot). Each core
 * boots its own U-Boot out of its own fip-<core>.bin, so each one can look in
 * its own directory. That means switching cores only has to swap fip.bin, and
 * no shared /extlinux/extlinux.conf has to be kept in sync. Swapping only
 * fip.bin used to leave the new core's U-Boot loading the other core's kernel,
 * which stops with "Bad Linux RISCV Image magic!".
 */
#undef  CONFIG_BOOTCOMMAND
#define CONFIG_BOOTCOMMAND \
    "sysboot mmc 0:1 any 0x82000000 /arm/extlinux/extlinux.conf"

#undef  CONFIG_EXTRA_ENV_SETTINGS
#define CONFIG_EXTRA_ENV_SETTINGS \
    "scriptaddr=0x82000000\0" \
    "kernel_addr_r=0x81000000\0" \
    "fdt_addr_r=0x88000000\0" \
    "ramdisk_addr_r=0x8a000000\0"
"""

# Find the final #endif guard and insert before it
guard = "#endif /* __CV181X_ASIC_H__ */"
if guard in src:
    src = src.replace(guard, insert + guard)
else:
    src = src + insert

with open("include/configs/cv181x-asic.h", "w") as f:
    f.write(src)
ENDPY

    # Patch 3: Provide the missing cv181x arm U-Boot control DTS.
    # The vendor tree (a955e4df) has no arch/arm/dts/cv181x_cv181xasic.dts.
    # The vendor dts/Makefile hardcodes DTB := arch/$(ARCH)/dts/$(CHIP)_$(CVIBOARD).dtb,
    # so with CHIP=cv181x CVIBOARD=cv181xasic it expects cv181x_cv181xasic.dtb.
    # This minimal self-contained DTS gives U-Boot a valid control FDT for:
    #   - fdtdec_setup_mem_size_base (reads /memory node)
    #   - driver model serial (snps,dw-apb-uart -> ns16550 DM driver)
    #   - driver model MMC (cvitek,cv181x-sd -> cvi_sdhci DM driver)
    # With CONFIG_OF_EMBED, U-Boot links this DTB in as __dtb_dt_begin so
    #   gd->fdt_blob is valid from startup without any runtime FDT pointer.
    # GIC base addresses from include/configs/cv181x-asic.h (cv181x-asic.h):
    #   GICD_BASE = 0x01F01000, GICC_BASE = 0x01F02000
    # SD node compatible "cvitek,cv181x-sd" matches sdhci-mars.c of_match
    #   (sdhci_cvi_sd_drvdata, index=MMC_TYPE_SD) which handles SDIO0 pad
    #   setup (cvi_sdio0_pad_function + cvi_sdio0_pad_setting) in its probe.
    cat > arch/arm/dts/cv181x_cv181xasic.dts <<'ENDDTS'
/dts-v1/;

/ {
	model = "SOPHGO SG2000 Milk-V Duo S (aarch64)";
	compatible = "milkv,duos", "sophgo,sg2000", "cvitek,cv181x";

	#address-cells = <2>;
	#size-cells = <2>;

	memory@80000000 {
		device_type = "memory";
		/* 512 MB DDR at 0x80000000; first 2 MB reserved for BL31 */
		reg = <0x00 0x80000000 0x00 0x20000000>;
	};

	chosen {
		stdout-path = "serial0:115200n8";
	};

	aliases {
		serial0 = &uart0;
		mmc0    = &sd;
	};

	cpus {
		#address-cells = <1>;
		#size-cells = <0>;

		cpu0: cpu@0 {
			device_type = "cpu";
			compatible = "arm,cortex-a53";
			reg = <0x0>;
			enable-method = "psci";
		};
	};

	psci {
		compatible = "arm,psci-0.2";
		method = "smc";
	};

	gic: interrupt-controller@1f01000 {
		compatible = "arm,gic-400", "arm,cortex-a15-gic";
		#interrupt-cells = <3>;
		interrupt-controller;
		reg = <0x00 0x01f01000 0x00 0x1000>,
		      <0x00 0x01f02000 0x00 0x2000>;
	};

	timer {
		compatible = "arm,armv8-timer";
		interrupts = <1 13 0xff01>,
		             <1 14 0xff01>,
		             <1 11 0xff01>,
		             <1 10 0xff01>;
		interrupt-parent = <&gic>;
	};

	soc {
		#address-cells = <2>;
		#size-cells = <2>;
		compatible = "simple-bus";
		ranges;

		uart0: serial@4140000 {
			compatible = "snps,dw-apb-uart";
			reg = <0x00 0x04140000 0x00 0x1000>;
			clock-frequency = <25000000>;
			reg-shift = <2>;
			reg-io-width = <4>;
			status = "okay";
		};

		sd: cv-sd@4310000 {
			compatible = "cvitek,cv181x-sd";
			reg = <0x00 0x04310000 0x00 0x1000>;
			reg-names = "core_mem";
			bus-width = <4>;
			cap-sd-highspeed;
			cap-mmc-highspeed;
			sd-uhs-sdr12;
			sd-uhs-sdr25;
			sd-uhs-sdr50;
			sd-uhs-sdr104;
			no-sdio;
			no-mmc;
			src-frequency = <375000000>;
			min-frequency = <400000>;
			max-frequency = <200000000>;
			64_addressing;
			reset_tx_rx_phy;
			reset-names = "sdhci";
			pll_index = <6>;
			pll_reg = <0x3002070>;
			status = "okay";
		};
	};
};
ENDDTS
  '';

  buildPhase = ''
    export HOME=$TMPDIR
    export CROSS_COMPILE=${crossPrefix}
    # This vendor tree uses ARCH=arm for both arm and arm64; arm64 is a
    # subarch under arch/arm/ (CONFIG_ARM=y, CONFIG_ARM64=y via Kconfig).
    # Using ARCH=arm64 would break because there is no arch/arm64/ directory.
    export ARCH=arm
    export PATH=${cc}/bin:${cc.bintools.bintools}/bin:$PATH
    # SOURCE_DATE_EPOCH=1 tells U-Boot's filechk_timestamp.h rule to use
    # a fixed epoch date instead of calling date(1) at build time.
    # This makes U_BOOT_DATE, U_BOOT_TIME, U_BOOT_BUILD_DATE and U_BOOT_EPOCH
    # constants in include/generated/timestamp_autogenerated.h deterministic.
    export SOURCE_DATE_EPOCH=1

    # CHIP=cv181x and CVIBOARD=cv181xasic are used by cvitek.mk and dts/Makefile.
    # STORAGE_TYPE=sd enables -DCONFIG_SD_BOOT via cvitek.mk.
    # OF_EMBED=y: arch/arm/dts/cv181x_cv181xasic.dts is compiled and
    # linked into the binary; no runtime FDT pointer needed.
    make \
      CHIP=cv181x \
      CVIBOARD=cv181xasic \
      STORAGE_TYPE=sd \
      CONFIG_USE_DEFAULT_ENV=y \
      CROSS_COMPILE=${crossPrefix} \
      ARCH=arm \
      -j$NIX_BUILD_CORES \
      cvitek_sg2000_milkv_duos_glibc_arm64_sd_defconfig

    # GCC 15 is stricter than GCC 12 which Sophgo targeted.
    # -Wno-enum-int-mismatch: cmd_process return type declared as int, defined as enum.
    # -Wno-format: board_f.c uses %d for ulong; harmless on 64-bit.
    # -Wno-error: treat remaining new warnings as warnings, not errors.
    make \
      CHIP=cv181x \
      CVIBOARD=cv181xasic \
      STORAGE_TYPE=sd \
      CONFIG_USE_DEFAULT_ENV=y \
      CROSS_COMPILE=${crossPrefix} \
      ARCH=arm \
      KCFLAGS="-Wno-enum-int-mismatch -Wno-format -Wno-error" \
      -j$NIX_BUILD_CORES \
      all
  '';

  installPhase = ''
    mkdir -p $out
    # u-boot.bin is the raw U-Boot binary (LOADER_2ND for fip packing)
    cp u-boot.bin $out/u-boot-raw.bin
    # Keep u-boot ELF and map for debugging
    cp u-boot $out/u-boot || true
    cp u-boot.map $out/u-boot.map || true
  '';

  meta = {
    description = "Sophgo SG2000 U-Boot 2021.10 for Milk-V Duo S (aarch64, SD boot)";
    license     = pkgs.lib.licenses.gpl2Plus;
  };
}
